# Generated by Django 4.2.17 on 2025-01-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_hobby_remove_userprofile_hobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
